spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 4

  datasource:
    url: jdbc:mysql://localhost:3306/hive?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 开发环境日志级别更高，方便调试
logging:
  level:
    my.hive_back.module: DEBUG  # 增加模块包的日志，方便调试
    my.hive_back.api: DEBUG  # 增加接口包的日志，方便调试 Swagger