package my.hive.domain.installation;

import my.hive.domain.installation.mapper.InstallationTaskInstallerMapper;
import my.hive.domain.installation.mapper.InstallationTaskMapper;
import my.hive.domain.installation.model.dto.InstallationTaskInstallerRequest;
import my.hive.domain.installation.model.dto.InstallationTaskStatusUpdateRequest;
import my.hive.domain.installation.model.entity.InstallationTask;
import my.hive.domain.installation.model.entity.InstallationTaskInstaller;
import my.hive.domain.installation.service.InstallationTaskService;
import my.hive.infrastructure.storage.BusinessAttachmentService;
import my.hive.shared.context.TenantPermissionContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import javax.sql.DataSource;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.when;

@SpringJUnitConfig(InstallationTaskInstallerTransactionIntegrationTest.Config.class)
class InstallationTaskInstallerTransactionIntegrationTest {

    @Autowired
    private InstallationTaskService service;

    @Autowired
    private InstallationTaskMapper taskMapper;

    @Autowired
    private InstallationTaskInstallerMapper installerMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        TenantPermissionContext.init("TENANT_A", 1L, Set.of());
        Mockito.reset(taskMapper, installerMapper);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS installation_task_tx_test (
                  id BIGINT PRIMARY KEY,
                  tenant_code VARCHAR(64) NOT NULL,
                  installation_status VARCHAR(64) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS installation_task_installer_tx_test (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_code VARCHAR(64) NOT NULL,
                  installation_task_id BIGINT NOT NULL,
                  installer_name VARCHAR(50) NOT NULL,
                  installer_phone VARCHAR(40) NOT NULL,
                  sort_order INT NOT NULL
                )
                """);
        jdbcTemplate.update("DELETE FROM installation_task_installer_tx_test");
        jdbcTemplate.update("DELETE FROM installation_task_tx_test");
        jdbcTemplate.update(
                "INSERT INTO installation_task_tx_test(id, tenant_code, installation_status) VALUES (11, 'TENANT_A', 'shipped_pending_install')"
        );
        jdbcTemplate.update("""
                INSERT INTO installation_task_installer_tx_test(
                  tenant_code, installation_task_id, installer_name, installer_phone, sort_order
                ) VALUES ('TENANT_A', 11, '旧人员', '100', 0)
                """);

        InstallationTask task = new InstallationTask();
        task.setId(11L);
        task.setTenantCode("TENANT_A");
        task.setOrderId("ORDER-11");
        task.setInstallationStatus("shipped_pending_install");
        when(taskMapper.selectOne(any())).thenReturn(task);
        doAnswer(invocation -> {
            InstallationTask updating = invocation.getArgument(0);
            return jdbcTemplate.update(
                    "UPDATE installation_task_tx_test SET installation_status = ? WHERE id = ? AND tenant_code = ?",
                    updating.getInstallationStatus(), updating.getId(), updating.getTenantCode()
            );
        }).when(taskMapper).updateById(any(InstallationTask.class));
        doAnswer(invocation -> jdbcTemplate.update(
                "DELETE FROM installation_task_installer_tx_test WHERE tenant_code = 'TENANT_A' AND installation_task_id = 11"
        )).when(installerMapper).delete(any());
        doAnswer(invocation -> {
            InstallationTaskInstaller installer = invocation.getArgument(0);
            jdbcTemplate.update("""
                    INSERT INTO installation_task_installer_tx_test(
                      tenant_code, installation_task_id, installer_name, installer_phone, sort_order
                    ) VALUES (?, ?, ?, ?, ?)
                    """,
                    installer.getTenantCode(), installer.getInstallationTaskId(), installer.getInstallerName(),
                    installer.getInstallerPhone(), installer.getSortOrder()
            );
            throw new IllegalStateException("forced installer persistence failure");
        }).when(installerMapper).insert(any(InstallationTaskInstaller.class));
    }

    @AfterEach
    void tearDown() {
        TenantPermissionContext.clear();
    }

    @Test
    void installerFailureRollsBackTaskUpdateAndOriginalInstallerDeletion() {
        InstallationTaskInstallerRequest installer = new InstallationTaskInstallerRequest();
        installer.setName("新人员");
        installer.setPhone("200");
        InstallationTaskStatusUpdateRequest request = new InstallationTaskStatusUpdateRequest();
        request.setId(11L);
        request.setStatus("completed_accepted");
        request.setInstallers(List.of(installer));

        assertThrows(IllegalStateException.class, () -> service.updateStatus(request));

        assertEquals("shipped_pending_install", jdbcTemplate.queryForObject(
                "SELECT installation_status FROM installation_task_tx_test WHERE id = 11",
                String.class
        ));
        assertEquals(List.of("旧人员:100"), jdbcTemplate.query(
                "SELECT installer_name, installer_phone FROM installation_task_installer_tx_test ORDER BY sort_order",
                (resultSet, rowNum) -> resultSet.getString(1) + ":" + resultSet.getString(2)
        ));
    }

    @Configuration
    @EnableTransactionManagement(proxyTargetClass = true)
    static class Config {

        @Bean
        DataSource dataSource() {
            return new DriverManagerDataSource(
                    "jdbc:h2:mem:installation-transaction;MODE=MySQL;DB_CLOSE_DELAY=-1",
                    "sa",
                    ""
            );
        }

        @Bean
        JdbcTemplate jdbcTemplate(DataSource dataSource) {
            return new JdbcTemplate(dataSource);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }

        @Bean
        InstallationTaskMapper installationTaskMapper() {
            return Mockito.mock(InstallationTaskMapper.class);
        }

        @Bean
        InstallationTaskInstallerMapper installationTaskInstallerMapper() {
            return Mockito.mock(InstallationTaskInstallerMapper.class);
        }

        @Bean
        BusinessAttachmentService businessAttachmentService() {
            return Mockito.mock(BusinessAttachmentService.class);
        }

        @Bean
        InstallationTaskService installationTaskService() {
            return new InstallationTaskService();
        }
    }
}
