CREATE TABLE IF NOT EXISTS `installation_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_code` VARCHAR(64) NOT NULL COMMENT '租户编码',
  `order_id` VARCHAR(64) NOT NULL COMMENT '订单号',
  `order_status` VARCHAR(40) NOT NULL DEFAULT 'completed' COMMENT '订单状态',
  `installation_status` VARCHAR(40) NOT NULL DEFAULT 'production_completed' COMMENT '安装状态：production_completed生产完成，shipped_pending_install已发货待安装，completed_accepted已完成已验收',
  `customer_name` VARCHAR(120) DEFAULT NULL COMMENT '客户名称',
  `customer_phone` VARCHAR(40) DEFAULT NULL COMMENT '客户电话',
  `project_name` VARCHAR(160) DEFAULT NULL COMMENT '项目名称',
  `brand_name` VARCHAR(120) DEFAULT NULL COMMENT '品牌名称',
  `order_category` VARCHAR(40) DEFAULT NULL COMMENT '订单小项',
  `goods_desc` VARCHAR(500) DEFAULT NULL COMMENT '商品描述',
  `total_quantity` INT DEFAULT NULL COMMENT '数量',
  `delivery_date` VARCHAR(40) DEFAULT NULL COMMENT '交付日期',
  `express_company` VARCHAR(120) DEFAULT NULL COMMENT '物流公司',
  `express_no` VARCHAR(120) DEFAULT NULL COMMENT '物流单号',
  `is_invoice` TINYINT NOT NULL DEFAULT 0 COMMENT '是否开票：0-否，1-是',
  `creator` VARCHAR(80) DEFAULT NULL COMMENT '订单创建人',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '订单备注',
  `order_attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '订单附件名称',
  `order_attachment_url` VARCHAR(500) DEFAULT NULL COMMENT '订单附件地址',
  `order_attachment_size` BIGINT DEFAULT NULL COMMENT '订单附件大小',
  `construction_personnel` VARCHAR(120) DEFAULT NULL COMMENT '施工人员信息',
  `construction_phone` VARCHAR(40) DEFAULT NULL COMMENT '施工人员电话',
  `construction_remark` VARCHAR(500) DEFAULT NULL COMMENT '施工备注',
  `special_exception_note` VARCHAR(1000) DEFAULT NULL COMMENT '特殊及异常情况说明',
  `attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '验收附件名称',
  `attachment_url` VARCHAR(500) DEFAULT NULL COMMENT '验收附件地址',
  `attachment_size` BIGINT DEFAULT NULL COMMENT '验收附件大小',
  `order_completed_time` DATETIME DEFAULT NULL COMMENT '订单完成时间',
  `accepted_time` DATETIME DEFAULT NULL COMMENT '验收完成时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_installation_task_order` (`tenant_code`, `order_id`),
  KEY `idx_installation_task_status` (`tenant_code`, `installation_status`, `update_time`),
  KEY `idx_installation_task_customer` (`tenant_code`, `customer_name`, `project_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='安装任务表';
