-- 公共操作日志表：由 D:\HiveCommon 的 @CollectLog AOP 自动写入
CREATE TABLE IF NOT EXISTS `operation_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `trace_id` VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
  `tenant_code` VARCHAR(64) DEFAULT NULL COMMENT '租户编码',
  `user_id` BIGINT DEFAULT NULL COMMENT '操作用户ID',
  `module` VARCHAR(64) NOT NULL COMMENT '业务模块',
  `action` VARCHAR(64) NOT NULL COMMENT '操作动作',
  `biz_type` VARCHAR(64) DEFAULT NULL COMMENT '业务类型',
  `biz_no` VARCHAR(128) DEFAULT NULL COMMENT '业务编号',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '操作说明',
  `log_level` VARCHAR(16) NOT NULL DEFAULT 'INFO' COMMENT '日志级别：INFO-信息，WARN-警告，ERROR-错误',
  `class_name` VARCHAR(255) DEFAULT NULL COMMENT '类名',
  `method_name` VARCHAR(128) DEFAULT NULL COMMENT '方法名',
  `request_method` VARCHAR(16) DEFAULT NULL COMMENT '请求方法',
  `request_uri` VARCHAR(500) DEFAULT NULL COMMENT '请求地址',
  `client_ip` VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
  `user_agent` VARCHAR(500) DEFAULT NULL COMMENT '客户端标识',
  `args_json` TEXT DEFAULT NULL COMMENT '脱敏后的入参',
  `result_json` TEXT DEFAULT NULL COMMENT '脱敏后的返回值',
  `success` TINYINT NOT NULL DEFAULT 1 COMMENT '是否成功：0-失败，1-成功',
  `slow` TINYINT NOT NULL DEFAULT 0 COMMENT '是否慢操作：0-否，1-是',
  `duration_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '耗时毫秒',
  `error_type` VARCHAR(255) DEFAULT NULL COMMENT '异常类型',
  `error_message` TEXT DEFAULT NULL COMMENT '异常信息',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_tenant_time` (`tenant_code`, `create_time`),
  KEY `idx_level_time` (`log_level`, `create_time`),
  KEY `idx_module_action_time` (`module`, `action`, `create_time`),
  KEY `idx_biz` (`biz_type`, `biz_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公共操作日志表';
