CREATE TABLE IF NOT EXISTS `print_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_code` varchar(50) NOT NULL COMMENT '租户编码',
  `task_no` varchar(64) NOT NULL COMMENT '打印任务号',
  `print_type` varchar(32) NOT NULL COMMENT '打印类型(label-标签, receipt-出库单)',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_no` varchar(100) DEFAULT NULL COMMENT '业务编号',
  `source_order_no` varchar(100) DEFAULT NULL COMMENT '来源单号',
  `template_id` bigint DEFAULT NULL COMMENT '模板ID',
  `template_name` varchar(100) DEFAULT NULL COMMENT '模板名称',
  `print_channel` varchar(32) DEFAULT NULL COMMENT '打印通道',
  `device_name` varchar(100) DEFAULT NULL COMMENT '打印设备名称',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态(0-待打印,1-已打印,2-失败,3-作废)',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '失败/重试次数',
  `max_retry` int NOT NULL DEFAULT '3' COMMENT '最大重试次数',
  `print_payload_json` json DEFAULT NULL COMMENT '打印数据快照',
  `error_message` varchar(500) DEFAULT NULL COMMENT '错误信息或任务说明',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `printed_time` datetime DEFAULT NULL COMMENT '打印完成时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_print_task_no` (`task_no`),
  KEY `idx_print_task_tenant_status` (`tenant_code`,`status`,`create_time`),
  KEY `idx_print_task_biz` (`tenant_code`,`print_type`,`biz_no`),
  KEY `idx_print_task_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='打印任务记录表';
