package my.hive.domain.aftersales.service;

import com.alibaba.fastjson2.JSON;
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;
import my.hive.domain.aftersales.mapper.*;
import my.hive.domain.aftersales.model.dto.*;
import my.hive.domain.aftersales.model.entity.*;
import my.hive.shared.context.TenantPermissionContext;
import my.hive.shared.exception.BusinessException;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import javax.sql.DataSource;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@SpringJUnitConfig(AfterSalesTreatmentTransactionTest.Config.class)
class AfterSalesTreatmentTransactionTest {
    @Autowired AfterSalesTreatmentService service;
    @Autowired AfterSalesTicketMapper tickets;
    @Autowired AfterSalesTreatmentMapper treatments;
    @Autowired AfterSalesPartMapper parts;
    @Autowired AfterSalesPartStockRecordMapper ledger;
    @Autowired JdbcTemplate jdbc;
    String partsJson;

    @BeforeEach void setup() {
        reset(tickets, treatments, parts, ledger);
        TableInfoHelper.initTableInfo(new org.apache.ibatis.builder.MapperBuilderAssistant(new org.apache.ibatis.session.Configuration(), "tx"), AfterSalesPart.class);
        jdbc.execute("CREATE TABLE IF NOT EXISTS treatment_tx_ticket(id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS treatment_tx_stock(id BIGINT PRIMARY KEY, qty INT)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS treatment_tx_round(id BIGINT PRIMARY KEY, status VARCHAR(32), version INT)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS treatment_tx_ledger(id BIGINT GENERATED BY DEFAULT AS IDENTITY, treatment_id BIGINT)");
        jdbc.update("DELETE FROM treatment_tx_ticket"); jdbc.update("DELETE FROM treatment_tx_stock"); jdbc.update("DELETE FROM treatment_tx_round"); jdbc.update("DELETE FROM treatment_tx_ledger");
        jdbc.update("INSERT INTO treatment_tx_ticket VALUES(1)"); jdbc.update("INSERT INTO treatment_tx_stock VALUES(10,10)");
        jdbc.update("INSERT INTO treatment_tx_round VALUES(2,'waiting_outbound',0)");
        var line = new AfterSalesTicketPart(); line.setPartId(10L); line.setQuantity(2); line.setLineStatus("pending");
        partsJson = JSON.toJSONString(List.of(line));
        when(tickets.selectOne(any())).thenAnswer(i -> {
            jdbc.queryForObject("SELECT id FROM treatment_tx_ticket WHERE id=1 FOR UPDATE", Long.class);
            var ticket = new AfterSalesTicket(); ticket.setId(1L); ticket.setTenantCode("T1"); ticket.setStatus("processing"); return ticket;
        });
        when(treatments.selectOne(any())).thenAnswer(i -> jdbc.queryForObject("SELECT * FROM treatment_tx_round WHERE id=2", (rs,n) -> {
            var record = new AfterSalesTreatment(); record.setId(2L); record.setTenantCode("T1"); record.setTicketId(1L); record.setSequenceNo(1);
            record.setStatus(rs.getString("status")); record.setVersion(rs.getInt("version")); record.setDetailsJson("{}"); record.setPartsJson(partsJson); return record;
        }));
        when(parts.selectOne(any())).thenAnswer(i -> {
            var part = new AfterSalesPart(); part.setId(10L); part.setStockQty(jdbc.queryForObject("SELECT qty FROM treatment_tx_stock WHERE id=10", Integer.class)); part.setVersion(0); return part;
        });
        when(parts.update(isNull(), any())).thenAnswer(i -> jdbc.update("UPDATE treatment_tx_stock SET qty=qty-2 WHERE id=10 AND qty>=2"));
        when(ledger.insert(any())).thenAnswer(i -> jdbc.update("INSERT INTO treatment_tx_ledger(treatment_id) VALUES(?)", ((AfterSalesPartStockRecord)i.getArgument(0)).getTreatmentId()));
        when(treatments.updateById(any())).thenAnswer(i -> {
            AfterSalesTreatment r = i.getArgument(0);
            return jdbc.update("UPDATE treatment_tx_round SET status=?,version=? WHERE id=2", r.getStatus(), r.getVersion());
        });
        initContext();
    }
    void initContext() { TenantPermissionContext.init("T1", 7L, Set.of("after_sales:part:outbound")); }
    @AfterEach void cleanup() { TenantPermissionContext.clear(); }
    AfterSalesTreatmentActionRequest action() { var r = new AfterSalesTreatmentActionRequest(); r.setVersion(0); return r; }

    @Test void failedSecondPartRollsBackFirstStockAndLedger() {
        var lines = JSON.parseArray(partsJson, AfterSalesTicketPart.class);
        var second = new AfterSalesTicketPart(); second.setPartId(11L); second.setQuantity(2); second.setLineStatus("pending"); lines.add(second); partsJson = JSON.toJSONString(lines);
        var count = new AtomicInteger();
        doAnswer(i -> count.incrementAndGet() == 1 ? jdbc.update("UPDATE treatment_tx_stock SET qty=qty-2 WHERE id=10") : 0).when(parts).update(isNull(), any());
        assertEquals(10, jdbc.queryForObject("SELECT qty FROM treatment_tx_stock WHERE id=10", Integer.class));
        assertThrows(BusinessException.class, () -> service.action(1L, 2L, "outbound", action()));
        assertEquals(10, jdbc.queryForObject("SELECT qty FROM treatment_tx_stock WHERE id=10", Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM treatment_tx_ledger", Integer.class));
        assertEquals("waiting_outbound", jdbc.queryForObject("SELECT status FROM treatment_tx_round WHERE id=2", String.class));
    }
    @Test void simultaneousOutboundOnlyCommitsOnce() throws Exception {
        var start = new CountDownLatch(1);
        try (var executor = Executors.newFixedThreadPool(2)) {
            Callable<Boolean> call = () -> { initContext(); start.await(); try { service.action(1L, 2L, "outbound", action()); return true; } catch (BusinessException expected) { return false; } finally { TenantPermissionContext.clear(); } };
            var first = executor.submit(call); var second = executor.submit(call); start.countDown();
            assertNotEquals(first.get(10, TimeUnit.SECONDS), second.get(10, TimeUnit.SECONDS));
        }
        assertEquals(8, jdbc.queryForObject("SELECT qty FROM treatment_tx_stock WHERE id=10", Integer.class));
        assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM treatment_tx_ledger", Integer.class));
    }

    @Configuration @EnableTransactionManagement
    static class Config {
        @Bean DataSource dataSource() { return new DriverManagerDataSource("jdbc:h2:mem:afterSalesTreatmentTx;DB_CLOSE_DELAY=-1", "sa", ""); }
        @Bean JdbcTemplate jdbcTemplate(DataSource ds) { return new JdbcTemplate(ds); }
        @Bean PlatformTransactionManager transactionManager(DataSource ds) { return new DataSourceTransactionManager(ds); }
        @Bean AfterSalesTreatmentService service() { return new AfterSalesTreatmentService(); }
        @Bean AfterSalesTicketMapper ticketMapper() { return mock(AfterSalesTicketMapper.class); }
        @Bean AfterSalesTreatmentMapper treatmentMapper() { return mock(AfterSalesTreatmentMapper.class); }
        @Bean AfterSalesPartMapper partMapper() { return mock(AfterSalesPartMapper.class); }
        @Bean AfterSalesPartStockRecordMapper stockRecordMapper() { return mock(AfterSalesPartStockRecordMapper.class); }
        @Bean static org.springframework.beans.factory.config.BeanFactoryPostProcessor imageValidationStub() {
            return factory -> factory.registerSingleton("afterSalesService", mock(AfterSalesService.class));
        }
    }
}
