-- 售后一期：工单、配件主数据、库存与出库流水均独立于布匹库存。
CREATE TABLE IF NOT EXISTS `after_sales_ticket` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_code` VARCHAR(50) NOT NULL,
  `ticket_no` VARCHAR(40) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `customer_name` VARCHAR(120) NOT NULL,
  `customer_phone` VARCHAR(32) DEFAULT NULL,
  `project_name` VARCHAR(200) NOT NULL,
  `contact_name` VARCHAR(80) DEFAULT NULL,
  `contact_phone` VARCHAR(32) DEFAULT NULL,
  `service_address` VARCHAR(500) DEFAULT NULL,
  `ticket_type` VARCHAR(32) NOT NULL COMMENT 'consultation/diagnosis/resend_parts/on_site_repair/motor_replacement',
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'draft/waiting_outbound/processing/closed/cancelled',
  `priority` VARCHAR(20) NOT NULL DEFAULT 'normal',
  `problem_desc` TEXT NOT NULL,
  `diagnosis` TEXT DEFAULT NULL,
  `resolution` TEXT DEFAULT NULL,
  `scheduled_time` DATETIME DEFAULT NULL,
  `technician_name` VARCHAR(80) DEFAULT NULL,
  `waybill_no` VARCHAR(80) DEFAULT NULL,
  `old_motor_info` VARCHAR(500) DEFAULT NULL,
  `return_old_motor` TINYINT NOT NULL DEFAULT 0,
  `attachment_urls_json` JSON DEFAULT NULL,
  `creator_user_id` BIGINT DEFAULT NULL,
  `creator_name` VARCHAR(80) DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_after_sales_ticket_no` (`tenant_code`,`ticket_no`),
  KEY `idx_after_sales_ticket_order` (`tenant_code`,`order_id`),
  KEY `idx_after_sales_ticket_status` (`tenant_code`,`status`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='售后工单';

CREATE TABLE IF NOT EXISTS `after_sales_part` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_code` VARCHAR(50) NOT NULL,
  `part_code` VARCHAR(64) NOT NULL,
  `part_name` VARCHAR(120) NOT NULL,
  `category` VARCHAR(80) DEFAULT NULL,
  `model_spec` VARCHAR(160) DEFAULT NULL,
  `unit` VARCHAR(20) NOT NULL DEFAULT '个',
  `stock_qty` INT NOT NULL DEFAULT 0,
  `reserved_qty` INT NOT NULL DEFAULT 0,
  `safety_stock` INT NOT NULL DEFAULT 0,
  `photo_url` VARCHAR(500) DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `version` INT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_after_sales_part_code` (`tenant_code`,`part_code`),
  KEY `idx_after_sales_part_name` (`tenant_code`,`part_name`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='售后配件库';

CREATE TABLE IF NOT EXISTS `after_sales_ticket_part` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_code` VARCHAR(50) NOT NULL,
  `ticket_id` BIGINT NOT NULL,
  `part_id` BIGINT NOT NULL,
  `part_code` VARCHAR(64) NOT NULL,
  `part_name` VARCHAR(120) NOT NULL,
  `model_spec` VARCHAR(160) DEFAULT NULL,
  `unit` VARCHAR(20) NOT NULL,
  `quantity` INT NOT NULL,
  `line_status` VARCHAR(24) NOT NULL DEFAULT 'pending' COMMENT 'pending/outbound/cancelled',
  `remark` VARCHAR(300) DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_after_sales_ticket_part_ticket` (`tenant_code`,`ticket_id`,`line_status`),
  KEY `idx_after_sales_ticket_part_part` (`tenant_code`,`part_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='售后工单配件明细';

CREATE TABLE IF NOT EXISTS `after_sales_part_stock_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_code` VARCHAR(50) NOT NULL,
  `part_id` BIGINT NOT NULL,
  `ticket_id` BIGINT DEFAULT NULL,
  `operate_type` VARCHAR(24) NOT NULL COMMENT 'in/out',
  `quantity` INT NOT NULL,
  `before_qty` INT NOT NULL,
  `after_qty` INT NOT NULL,
  `operator_user_id` BIGINT DEFAULT NULL,
  `operator_name` VARCHAR(80) DEFAULT NULL,
  `remark` VARCHAR(300) DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_after_sales_stock_record_part` (`tenant_code`,`part_id`,`create_time`),
  KEY `idx_after_sales_stock_record_ticket` (`tenant_code`,`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='售后配件库存流水';
