CREATE TABLE IF NOT EXISTS `operation_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trace_id` varchar(64) NOT NULL,
  `tenant_code` varchar(64) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `module` varchar(64) NOT NULL,
  `action` varchar(64) NOT NULL,
  `biz_type` varchar(64) DEFAULT NULL,
  `biz_no` varchar(128) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `log_level` varchar(16) NOT NULL DEFAULT 'INFO',
  `class_name` varchar(255) DEFAULT NULL,
  `method_name` varchar(128) DEFAULT NULL,
  `request_method` varchar(16) DEFAULT NULL,
  `request_uri` varchar(500) DEFAULT NULL,
  `client_ip` varchar(64) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `args_json` text,
  `result_json` text,
  `success` tinyint NOT NULL DEFAULT 1,
  `slow` tinyint NOT NULL DEFAULT 0,
  `duration_ms` bigint NOT NULL DEFAULT 0,
  `error_type` varchar(255) DEFAULT NULL,
  `error_message` text,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_tenant_time` (`tenant_code`, `create_time`),
  KEY `idx_level_time` (`log_level`, `create_time`),
  KEY `idx_module_action_time` (`module`, `action`, `create_time`),
  KEY `idx_biz` (`biz_type`, `biz_no`),
  KEY `idx_operation_log_tenant_level_time` (`tenant_code`, `log_level`, `create_time`),
  KEY `idx_operation_log_success_time` (`success`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
