CREATE TABLE IF NOT EXISTS `system_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `event_key` VARCHAR(120) NOT NULL COMMENT 'Event unique key',
  `source_app` VARCHAR(80) NOT NULL COMMENT 'Source application',
  `event_type` VARCHAR(80) NOT NULL COMMENT 'Event type',
  `level` VARCHAR(20) NOT NULL COMMENT 'INFO/WARN/ERROR',
  `tenant_code` VARCHAR(50) DEFAULT NULL COMMENT 'Tenant code',
  `module` VARCHAR(80) DEFAULT NULL COMMENT 'Module name',
  `title` VARCHAR(180) NOT NULL COMMENT 'Event title',
  `content` VARCHAR(1000) DEFAULT NULL COMMENT 'Event content',
  `biz_type` VARCHAR(80) DEFAULT NULL COMMENT 'Business type',
  `biz_no` VARCHAR(160) DEFAULT NULL COMMENT 'Business number',
  `trace_id` VARCHAR(80) DEFAULT NULL COMMENT 'Trace id',
  `detail_json` JSON DEFAULT NULL COMMENT 'Structured event detail',
  `handled` TINYINT NOT NULL DEFAULT 0 COMMENT '0=unhandled, 1=handled',
  `handled_by` VARCHAR(80) DEFAULT NULL COMMENT 'Handler',
  `handled_time` DATETIME DEFAULT NULL COMMENT 'Handled time',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  PRIMARY KEY (`id`),
  KEY `idx_system_event_level_time` (`level`, `create_time`),
  KEY `idx_system_event_type_time` (`event_type`, `create_time`),
  KEY `idx_system_event_source_time` (`source_app`, `create_time`),
  KEY `idx_system_event_tenant_time` (`tenant_code`, `create_time`),
  KEY `idx_system_event_handled` (`handled`, `level`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='System important event table';
