CREATE TABLE IF NOT EXISTS `installation_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_code` varchar(64) NOT NULL,
  `order_id` varchar(64) NOT NULL,
  `order_status` varchar(40) NOT NULL DEFAULT 'completed',
  `installation_status` varchar(40) NOT NULL DEFAULT 'production_completed',
  `customer_name` varchar(120) DEFAULT NULL,
  `customer_phone` varchar(40) DEFAULT NULL,
  `project_name` varchar(160) DEFAULT NULL,
  `brand_name` varchar(120) DEFAULT NULL,
  `order_category` varchar(40) DEFAULT NULL,
  `goods_desc` varchar(500) DEFAULT NULL,
  `total_quantity` int DEFAULT NULL,
  `delivery_date` varchar(40) DEFAULT NULL,
  `express_company` varchar(120) DEFAULT NULL,
  `express_no` varchar(120) DEFAULT NULL,
  `is_invoice` tinyint NOT NULL DEFAULT 0,
  `creator` varchar(80) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `order_attachment_name` varchar(255) DEFAULT NULL,
  `order_attachment_url` varchar(500) DEFAULT NULL,
  `order_attachment_size` bigint DEFAULT NULL,
  `construction_personnel` varchar(120) DEFAULT NULL,
  `construction_phone` varchar(40) DEFAULT NULL,
  `construction_remark` varchar(500) DEFAULT NULL,
  `attachment_name` varchar(255) DEFAULT NULL,
  `attachment_url` varchar(500) DEFAULT NULL,
  `attachment_size` bigint DEFAULT NULL,
  `order_completed_time` datetime DEFAULT NULL,
  `accepted_time` datetime DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_installation_task_order` (`tenant_code`, `order_id`),
  KEY `idx_installation_task_status` (`tenant_code`, `installation_status`, `update_time`),
  KEY `idx_installation_task_customer` (`tenant_code`, `customer_name`, `project_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
